# Generated by Django 5.2.3 on 2025-07-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_memo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
